info:
  contact: {}
paths:
  /:
    get:
      description: do ping
      responses:
        "200":
          description: '{"message":"hello world"}'
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
